### ISSUE TITLE
DataHub Upgrade v1.5.0 fails to initialize Kafka Producer with SASL/OAUTHBEARER due to missing jose4j classes (NoClassDefFoundError)of the bug

### ISSUE THREAD

**Issue by sivarajasekhar** [datahub-project/datahub#18733]
## Describe the bug

After upgrading DataHub from **v1.3.0.1** to **v1.5.0**, our deployment is no longer able to initialize the Kafka producer when connecting to a Strimzi Kafka cluster secured with **SASL_SSL + OAUTHBEARER (Azure AD OAuth2)**.

The exact same Kubernetes environment, Kafka cluster, OAuth configuration, certificates, Helm values, and secrets work correctly with **DataHub v1.3.0.1**.

During startup, the `system-update` job fails while creating the Kafka producer. The root cause is:

```
java.lang.NoClassDefFoundError:
org/jose4j/keys/resolvers/VerificationKeyResolver
```

which eventually causes

```
org.apache.kafka.common.KafkaException:
Failed to construct kafka producer
```

and the Spring context fails to initialize.

After inspecting the DataHub upgrade JARs, we found that:

* DataHub v1.3.0.1 contains `nimbus-jose-jwt-10.0.1.jar`
* DataHub v1.5.0 no longer contains any JOSE library (`nimbus-jose-jwt` or `jose4j`)
* Both versions ship the same Kafka libraries:

  * spring-kafka-3.3.8
  * kafka-clients-8.0.0-ccs
  * kafka-avro-serializer-8.0.0
  * kafka-schema-registry-client-8.0.0

The Kafka client attempts to instantiate the OAuth login callback handler, but fails because the required JOSE class is missing from the runtime classpath.

---

## To Reproduce

1. Deploy DataHub **v1.5.0** using Helm.
2. Configure Kafka with:

   * `security.protocol=SASL_SSL`
   * `sasl.mechanism=OAUTHBEARER`
   * Azure AD OAuth token endpoint
   * Strimzi Kafka
3. Start the `system-update` job.
4. Observe startup failure before any Kafka connection is established.

Example configuration:

```
datahub:
  global:
    springKafkaConfigurationOverrides:
      security.protocol: SASL_SSL
      sasl.mechanism: OAUTHBEARER
      sasl.login.callback.handler.class: org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginCallbackHandler
      sasl.oauthbearer.token.endpoint.url: "https://login.microsoftonline.com/XXXXXXXXXX/oauth2/v2.0/token"
      ssl.truststore.location: /etc/credentials/kafka-jks-truststore/kafka-truststore.jks
      ssl.truststore.type: JKS
      ssl.truststore.password: "<XXXXX>"
      ssl.endpoint.identification.algorithm: https
      bearer.auth.credentials.source: OAUTHBEARER
      bearer.auth.issuer.endpoint.url: "https://login.microsoftonline.com/XXXXXXXXXXXXX/oauth2/v2.0/token"
      bearer.auth.client.id: "XXXXXXXXX"
      bearer.auth.client.secret: "XXXXXXXXXXXXXXX"
      bearer.auth.scope: "XXXXXXXXXXXXXXXXXXXXX/.default"
      schema.registry.ssl.truststore.location: /etc/credentials/kafka-jks-truststore/kafka-truststore.jks
      schema.registry.ssl.truststore.password: "XXXXXXXXXXX"
      schema.registry.ssl.truststore.type: JKS
      schema.registry.ssl.keystore.location: /etc/credentials/kafka-jks-truststore/kafka-truststore.jks
      schema.registry.ssl.keystore.password: "XXXXXXX"
      schema.registry.ssl.keystore.type: JKS
```

---

## Expected behavior

DataHub v1.5.0 should behave the same as v1.3.0.1 and successfully initialize the Kafka producer when using SASL/OAUTHBEARER authentication.

The application should not fail because of missing runtime dependencies.

---

## Actual behavior

Startup fails with:

```
Caused by: java.lang.NoClassDefFoundError:
org/jose4j/keys/resolvers/VerificationKeyResolver
```

followed by

```
KafkaException: Failed to construct kafka producer
```

which causes:

```
Failed to instantiate kafkaProducer
```

and the Spring application exits during initialization.

---

## Environment

* DataHub Version: **v1.5.0**
* Previous Working Version: **v1.3.0.1**
* Deployment: Helm / Kubernetes
* Kafka: Strimzi
* Authentication: SASL_SSL + OAUTHBEARER
* OAuth Provider: Azure AD
* Schema Registry: Confluent Schema Registry
* JDK: Java 21 (container image)

---

## Investigation

We compared the packaged libraries inside the upgrade JARs.

Both versions contain:

```
spring-kafka-3.3.8
kafka-clients-8.0.0-ccs
kafka-avro-serializer-8.0.0
```

However:

### v1.3.0.1

Contains:

```
BOOT-INF/lib/nimbus-jose-jwt-10.0.1.jar
```

### v1.5.0

No JOSE-related libraries are packaged.

Since the runtime later throws:

```
ClassNotFoundException:
org.jose4j.keys.resolvers.VerificationKeyResolver
```

it appears that a required runtime dependency for Kafka OAuth support is no longer available on the classpath.

We would like to know whether this removal was intentional or if it is a packaging regression in the v1.5.0 upgrade image.

---

## Screenshots / Logs

Key stack trace:

```
java.lang.NoClassDefFoundError:
org/jose4j/keys/resolvers/VerificationKeyResolver

Caused by:
KafkaException: Failed to construct kafka producer
```

Complete logs can be provided if required.
