### ISSUE TITLE
Breaking change in tableau ingestion

### ISSUE THREAD

**Issue by maaaikoool** [datahub-project/datahub#7575]
**Describe the bug**
After the changes introduced [here](https://github.com/datahub-project/datahub/pull/7426/files#diff-015e0d583af03606c1bad3733db5cda92eed9b1dcbb6b8cc6d5c74fd2ebad226R45) we are using a field `projectLuid` that was introduced in Tableau Cloud June 2022 / Server 2022.3.

This is a breaking change, we should either make it explicit [here](https://github.com/datahub-project/datahub/pull/7426/files#diff-9a69800355baee2a7495dab637dd6bb46ba1f3be3a6b73bbc7bc70c22b9aa07fR5) or find a workaround.

[Tableau releases](https://help.tableau.com/current/api/metadata_api/en-us/docs/meta_api_release_notes.html)

**To Reproduce**
1. Ingest from Tableau using a version previous to 2022.3
1. Ingestion fails with error `Validation error of type FieldUndefined: Field 'projectLuid' in type 'Workbook' is undefined @ 'workbooksConnection/nodes/projectLuid'`

**Expected behavior**
Ingestion should continue to work with versions > 2021.1.10.

**Screenshots**
![image](https://user-images.githubusercontent.com/3258096/224946807-d10421a4-2aa0-4f9d-aea6-4876bb893bf0.png)

**Comment by hsheth2** [comment]
@mohdsiddique this looks like a real regression / issue with https://github.com/datahub-project/datahub/pull/7483 or https://github.com/datahub-project/datahub/pull/7426.

Is there any way to avoid this, or do we need to make our requirements more explicit?

**Comment by lusob** [comment]
I'm also experiencing this issue with the `projectLuid` field being introduced in a later version of Tableau than what I'm currently using. It's definitely a breaking change that affects backward compatibility, and I agree that finding a workaround or making it explicit in the documentation would be helpful.

Has anyone found a solution or workaround for this yet? If not, let's work together to find a solution that works for everyone impacted.

Thanks for letting us know @maaaikoool

**Comment by bossenti** [comment]
We are facing the same issue when trying to migrate from DataHub `0.9.6` to `0.10.1`.
See [this](https://datahubspace.slack.com/archives/CUMUWQU66/p1680591213122649) slack thread for some context

I would really appreciate a workaround as this prevents us from adopting a newer version than 0.9.6 (I would assume that for most teams/setups, upgrading Tableau is out of reach or not easily possible)

**Comment by jjoyce0510** [comment]
Folks while we work to figure this out please continue to use the v0.9.6 ingestion source for your PowerBI recipe :)
