### ISSUE TITLE
Superset source crash when display_uri is not set

### ISSUE THREAD

**Issue by daha** [datahub-project/datahub#5709]
**Describe the bug**

Ingesting with superset source crash when connect_uri is set and not display_uri. This was introduced in #5408.

**To Reproduce**

Recipe config:
``` yaml
source:
  type: "superset"
  config:
    username: datahub
    password: datahub
    provider: db
    connect_uri: https://somehost/
```

Run `datahub ingest -c <recipe-file>` with a file like above (either with a link specified or with DATAHUB_GMS_URL).

This results in the following error:
```
[2022-08-23 05:48:51,418] ERROR    {datahub.ingestion.run.pipeline:127} - 'dict' object has no attribute 'set'
Traceback (most recent call last):
  File "/home/airflow/venv.datahub/lib/python3.9/site-packages/datahub/ingestion/run/pipeline.py", line 178, in __init__
    self.source: Source = source_class.create(
  File "/home/airflow/venv.datahub/lib/python3.9/site-packages/datahub/ingestion/source/superset.py", line 167, in create
    config = SupersetConfig.parse_obj(config_dict)
  File "pydantic/main.py", line 521, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1082, in pydantic.main.validate_model
  File "/home/airflow/venv.datahub/lib/python3.9/site-packages/datahub/ingestion/source/superset.py", line 87, in default_display_uri_to_connect_uri
    values.set("display_uri", values.get("connect_uri"))
```

**Expected behavior**
It should not crash when display_uri is not set. 

`values` in this case which is Python dict does not have a set method. The code on line 87,https://github.com/datahub-project/datahub/blob/865074e338d5e9905236dbfd90ba43170c6d2e1c/metadata-ingestion/src/datahub/ingestion/source/superset.py#L87 should either be
``` python
    values["display_uri"] = values.get("connect_uri")
```

or
``` python
    values.update(display_uri=values.get("connect_uri"))
```

**Desktop (please complete the following information):**
 - DATAHUB_VERSION=0.8.43.1

**Additional context**

**Comment by shirshanka** [comment]
fixed via #5711
