### ISSUE TITLE
`acryl-datahub-airflow-plugin` incompatible with Airflow 2.4.x

### ISSUE THREAD

**Issue by jdu** [datahub-project/datahub#6145]
**Describe the bug**

`acryl-datahub-airflow-plugin` does not work with the latest release of Airflow. 

```
[2022-10-07T08:03:31.044+0000] INFO - Exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/datahub_airflow_plugin/datahub_plugin.py", line 337, in custom_on_success_callback
    datahub_on_success_callback(context)
  File "/usr/local/lib/python3.9/site-packages/datahub_airflow_plugin/datahub_plugin.py", line 190, in datahub_on_success_callback
    inlets = get_inlets_from_task(task, context)
  File "/usr/local/lib/python3.9/site-packages/datahub_airflow_plugin/datahub_plugin.py", line 44, in get_inlets_from_task
    and isinstance(task._inlets, list)
AttributeError: 'TaskOperator' object has no attribute '_inlets'
```

**To Reproduce**
1. Install Airflow 2.4.1
2. Install acryl-datahub-airflow-plugin
3. Configure connection
4. Import `datahub_provider.entities.Dataset` and add an outlet to a task
5. Run airflow workflow

**Expected behavior**
The datahub_provider plugin produces the metadata and sends it to Datahub.

**Screenshots**
N/A

**Desktop (please complete the following information):**

**Additional context**

This was working fine on airflow 2.3.x but it seems that airflow has changed some of the semantics around how you access inlets/outlets from airflow `BaseOperator` classes in hooks. 

`TaskOperator` here is a extension of `KubernetesPodOperator`, this was previously working fine on 2.3.x airflow.

**Comment by andrewkomkov** [comment]
Having the same issue

**Comment by jdu** [comment]
@andrewkomkov I pulled the package from pypi and edited the references to `_inlets` and `_outlets` in the code to use `inlets` and `outlets`, generally an underscore-prefixed variable in python is prefixed to denote that it's private and shouldn't be relied on. Doing that, and removing the sqlalchemy and airflow from setup.py requires, I could then install and get it working with `pip install <folder_holding_the_package>` instead of from pypi.

If you're stuck like we were that'll get you around it for now.

**Comment by jdu** [comment]
There's a lingering problem as well in that airflow how has it's own `from airflow import Dataset` which goes into `outlets` / `inlets` for dataset-based scheduling and using that feature will break the datahub ingestion post-task execution.

**Comment by fjmacagno** [comment]
Any plans to fix this? I would rather avoid putting a manual patch into prod if i can.
